### ISSUE TITLE
Different with native function (atob/btoa)

### ISSUE THREAD

**Issue by kunashir** [stranger82/angular-utf8-base64#9]
Good day!

What a different with native function?
I hava a string with base64 data and try to decode it and create blob object:

var blob = new Blob([ atob(attchment_data) ], {type: "image/jpg"});
var blob22 = new Blob([ base64.decode(attchment_data)], {type: "image/jpg"});

But: 
blob.size = 124375
blob22.size = 80221

Posible I don't understand right way to decoding base64 string... but I don't create file from base64 data if it's not text file.

**Comment by th3m477** [comment]
atob() functions only work with ASCii, this module is for UTF8 support (which you will find is more commonly needed).
